# Generated by Django 6.0.6 on 2026-06-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_brand_options_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='billing.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Grupos', to='billing.productgroup', verbose_name='Grupo'),
        ),
    ]
