# Generated by Django 6.0.6 on 2026-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_estado_invoice_saldo_invoice_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_apikey',
            field=models.CharField(blank=True, help_text='Solo necesaria si el cliente se suscribió a CallMeBot para recibir notificaciones.', max_length=20, null=True, verbose_name='WhatsApp API Key (CallMeBot)'),
        ),
    ]
