# Generated by Django 6.0.6 on 2026-07-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_customer_whatsapp_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='whatsapp_apikey',
        ),
    ]
