# Generated by Django 6.0.6 on 2026-07-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrofactura',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('paypal', 'PayPal'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=15, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='cobrofactura',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='ID de transacción de PayPal u otro medio externo, para trazabilidad.', max_length=100, null=True, verbose_name='Referencia Externa'),
        ),
    ]
