# Generated by Django 6.0.6 on 2026-07-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('export_pdf', 'Puede exportar reportes a PDF'), ('export_excel', 'Puede exportar reportes a Excel')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
