# Generated by Django 6.0.6 on 2026-07-11 22:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser mayor que cero.')], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El costo unitario debe ser mayor que cero.')], verbose_name='Costo Unitario'),
        ),
    ]
